### PR TITLE
Allow containers-0.6 (bundled with GHC 8.6)

### PR DESCRIPTION
**Pull request by ckoparkar**
And start testing with GHC 8.6.

### CODE REVIEW

**Comment by ckoparkar** [comment]
@mainland ping :)

**Comment by ckoparkar** [comment]
@mainland ping :)

**Comment by gwils** [comment]
As a hackage trustee, I have revised the most recent release of symbol to relax this bound to `< 0.7`. It would still be worthwhile to merge this pull request.

**Comment by ckoparkar** [comment]
@mainland another ping :)

**Comment by ckoparkar** [comment]
@mainland ping :)

**Comment by mainland** [comment]
Apologies for being so tardy, but an equivalent fix is in b5087588.

**Pull request closed without merging**
